services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    # restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # restart: always